name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make install_dependencies
      
    - name: Make
      run: make
      
  upload_artifact:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/upload-artifact@v3
      with:
        name: commands
        path: ./dist/commands
  
